export const FETCH_WISHLIST_REQUEST = "FETCH_WISHLIST_REQUEST";
export const FETCH_WISHLIST_SUCCESS = "FETCH_WISHLIST_SUCCESS";
export const FETCH_WISHLIST_FAILURE = "FETCH_WISHLIST_FAILURE";

export const ADD_TO_WISHLIST_REQUEST = "ADD_TO_WISHLIST_REQUEST";
export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS";
export const ADD_TO_WISHLIST_FAILURE = "ADD_TO_WISHLIST_FAILURE";

export const REMOVE_FROM_WISHLIST_REQUEST = "REMOVE_FROM_WISHLIST_REQUEST";
export const REMOVE_FROM_WISHLIST_SUCCESS = "REMOVE_FROM_WISHLIST_SUCCESS";
export const REMOVE_FROM_WISHLIST_FAILURE = "REMOVE_FROM_WISHLIST_FAILURE";

export const CLEAR_WISHLIST_REQUEST = "CLEAR_WISHLIST_REQUEST";
export const CLEAR_WISHLIST_SUCCESS = "CLEAR_WISHLIST_SUCCESS";
export const CLEAR_WISHLIST_FAILURE = "CLEAR_WISHLIST_FAILURE";

export const IS_PRODUCT_IN_WISHLIST_REQUEST = "IS_PRODUCT_IN_WISHLIST_REQUEST";
export const IS_PRODUCT_IN_WISHLIST_SUCCESS = "IS_PRODUCT_IN_WISHLIST_SUCCESS";
export const IS_PRODUCT_IN_WISHLIST_FAILURE = "IS_PRODUCT_IN_WISHLIST_FAILURE";