export const CONTINUE_WITH_GOOGLE_REQUEST = "CONTINUE_WITH_GOOGLE_REQUEST";
export const CONTINUE_WITH_GOOGLE_SUCCESS = "CONTINUE_WITH_GOOGLE_SUCCESS";
export const CONTINUE_WITH_GOOGLE_FAILURE = "CONTINUE_WITH_GOOGLE_FAILURE";