export const SEND_OTP_FORGOT_PASSWORD_REQUEST = "SEND_OTP_FORGOT_PASSWORD_REQUEST";
export const SEND_OTP_FORGOT_PASSWORD_SUCCESS = "SEND_OTP_FORGOT_PASSWORD_SUCCESS";
export const SEND_OTP_FORGOT_PASSWORD_FAILURE = "SEND_OTP_FORGOT_PASSWORD_FAILURE";

export const VERIFY_OTP_FORGOT_PASSWORD_REQUEST = "VERIFY_OTP_FORGOT_PASSWORD_REQUEST";
export const VERIFY_OTP_FORGOT_PASSWORD_SUCCESS = "VERIFY_OTP_FORGOT_PASSWORD_SUCCESS";
export const VERIFY_OTP_FORGOT_PASSWORD_FAILURE = "VERIFY_OTP_FORGOT_PASSWORD_FAILURE";

export const SET_NEW_PASSWORD_REQUEST = "SET_NEW_PASSWORD_REQUEST";
export const SET_NEW_PASSWORD_SUCCESS = "SET_NEW_PASSWORD_SUCCESS";
export const SET_NEW_PASSWORD_FAILURE = "SET_NEW_PASSWORD_FAILURE";