export const FETCH_HOME_PAGE_DATA_REQUEST = 'FETCH_HOME_PAGE_DATA_REQUEST';
export const FETCH_HOME_PAGE_DATA_SUCCESS = 'FETCH_HOME_PAGE_DATA_SUCCESS';
export const FETCH_HOME_PAGE_DATA_FAILURE = 'FETCH_HOME_PAGE_DATA_FAILURE';